name: banking_client
description: A banking lab control panel
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.1.3
  flutter: ^3.13.6

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.3
  auto_route: ^7.8.4
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  dropdown_button2: ^2.3.9
  datepicker_dropdown: ^0.1.0
  vph_web_date_picker: ^0.0.5
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - resources/lang/

  fonts:
    - family: Sans Serif
      fonts:
        - asset: resources/font/TT-Corals-Trial-Regular.otf
          style: normal
