name: banking_client
description: A banking lab control panel
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.1.3
  flutter: ^3.13.6

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ./packages/core
  data:
    path: ./packages/data
  navigation:
    path: ./packages/navigation

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - resources/lang/

  fonts:
    - family: Sans Serif
      fonts:
        - asset: resources/font/TT-Corals-Trial-Regular.otf
          style: normal
