name: core_ui
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3
  flutter: ^3.13.6

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  flutter_bloc: ^8.1.3
  auto_route: ^7.8.4
  dropdown_button2: ^2.3.9
  vph_web_date_picker: ^0.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
