name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3
  flutter: ^3.13.6

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../domain

  easy_localization: ^3.0.3
  get_it: ^7.6.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
