name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3
  flutter: ^3.13.6

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1

  core:
    path: ../core

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
